{{
  config({    
    "materialized": "ephemeral"
  })
}}

WITH sq_v_adgapd1 AS (

  SELECT * 
  
  FROM {{ source('toolkit_e2e_v9_source', 'sq_v_adgapd1') }}

)
,

lkp_guest_appointment AS (

  SELECT *
  
  FROM sq_v_adgapd1 AS in0
  LEFT JOIN UNKNOWN AS in1
     ON TRUE /* TODO: define lookup join condition */

)
,

exp_guest_appointment AS (

  SELECT 
    GUEST_APPOINTMENT_ID AS GUEST_APPOINTMENT_ID,
    GUEST_ID AS GUEST_ID,
    BOOKING_ID AS BOOKING_ID,
    OFFERED_INVENTORY_ID AS OFFERED_INVENTORY_ID,
    CREATION_USER_ID AS CREATION_USER_ID,
    CREATION_DTM AS CREATION_DTM,
    LAST_UPDATE_USER_ID AS LAST_UPDATE_USER_ID,
    LAST_UPDATE_DTM AS LAST_UPDATE_DTM,
    ACTIVE_FLAG AS ACTIVE_FLAG,
    ASR_BOOKING_ID AS ASR_BOOKING_ID,
    GUEST_APPOINTMENT_DATE AS GUEST_APPOINTMENT_DATE,
    GUEST_APPOINTMENT_TIME_DESC AS GUEST_APPOINTMENT_TIME_DESC,
    PRODUCT_CODE AS PRODUCT_CODE,
    PRODUCT_DESC AS PRODUCT_DESC,
    GRANTOR_GUEST_ID AS GRANTOR_GUEST_ID,
    GRANTOR_BOOKING_ID AS GRANTOR_BOOKING_ID,
    ABSHIP AS ABSHIP,
    ABSDDT_DT AS ABSDDT_DT,
    CASE AUDIT_ID WHEN NULL THEN -1 ELSE AUDIT_ID END AS OUT_AUDIT_ID,
    OLD_GUEST_APPOINTMENT_ID AS OLD_GUEST_APPOINTMENT_ID
  
  FROM sq_v_adgapd1 AS in0

)
,

fil_existing_data AS (

  SELECT *
  
  FROM exp_guest_appointment AS in0
  
  WHERE IF(OLD_GUEST_APPOINTMENT_ID IS NULL, TRUE, FALSE)

)


SELECT *


FROM fil_existing_data
